version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    env_file:
      - ./.env
    depends_on:
      - postgres
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_USER: docker
      POSTGRES_DB: content
    env_file:
      - ./.env
    ports:
      - 5432:5432
    expose:
      - 5432
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
    depends_on:
      - web
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    environment:
        - discovery.type=single-node
        - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    expose:
      - 9200
    depends_on:
      - web
  redis:
    image: redis
    container_name: redis
    expose:
      - 6379
  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - elasticsearch
      - redis
      - web
    env_file:
      - ./.env
volumes:
  postgres_data:
  static_volume:
  media_volume: